management:
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    application:
        name: expensestracker
    datasource:
        url: jdbc:h2:tcp://localhost/~/example
        username: sa
        password:
        driver-class-name: org.h2.Driver
        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    h2:
        console:
            enabled: true